### ISSUE TITLE
Where is the CompositionGenerator function?

### ISSUE THREAD

**Issue by jiali1025** [chentl/MatAL#1]
I am curious where is the CompositionGenerator function in your code, it seems to be an important part in your active learning method. It shows you imported it from matal.ml. However, I didn't find this function at all.

**Comment by chentl** [comment]
Apologies for the oversight! It seems the newest version never got committed. I have now uploaded the code. Please let me know if there are any other issues. Thanks!

**Comment by liuyiming7788** [comment]
> Apologies for the oversight! It seems the newest version never got committed. I have now uploaded the code. Please let me know if there are any other issues. Thanks!

Hello Dr. Chen. I would like to learn the code in your project for a fee. Can you teach me ？This is my email address 376650812@qq.com, I look forward to your contact
