### ISSUE TITLE
Where is the training data？

### ISSUE THREAD

**Issue by Wokkk141170** [chentl/MatAL#2]
In the process of reproducing the code, I am missing the relevant training data so that I cannot reproduce it. Could you provide us with the specific training data and the relevant missing data, thank you very much!

**Comment by chentl** [comment]
Hi, all training and testing data for the paper are available at [https://zenodo.org/records/7916361](https://zenodo.org/records/7916361). (In that repository, DB is for Design Boundary and AL is for Active Learning). Let me know if you have any other issues.

**Comment by Wokkk141170** [comment]
Thank you very much for your reply!
